### ISSUE TITLE
:sparkles: Exclude unused enums

### ISSUE THREAD

**Issue by FH-Inway** [shashisadasivan/EDMXTrimmer#11]
The tool currently does a good job of removing most of the stuff that is not needed after removing the entities that were not specified to be kept. However, the enums are not trimmed, which causes unnecessary content in the output file.

I propose to also remove the enums that are not required by the remaining entities or their actions.

**Comment by shashisadasivan** [comment]
Thanks for adding this. Please update the readme file if relevant.
Thank you heaps @FH-Inway 👍🏽
