### ISSUE TITLE
Add build action for pull requests

### ISSUE THREAD

**Issue by FH-Inway** [shashisadasivan/EDMXTrimmer#15]
To have some basic automated validation of pull requests, a build action should be added.

This could look similar to https://github.com/FH-Inway/EDMXTrimmer/blob/fh-main/.github/workflows/build-release.yml
See https://github.com/FH-Inway/EDMXTrimmer/actions/runs/4096944914 for an example run of that action.

**Comment by shashisadasivan** [comment]
Thanks @FH-Inway . Lots to learn here for me. For the time being i have copied over your build file and chucked it in here. Seems to have built fine

**Comment by FH-Inway** [comment]
@shashisadasivan Looks good. I will work on it a bit so that it gets executed automatically when someone creates a pr.
