### ISSUE TITLE
Option to exclude entities

### ISSUE THREAD

**Issue by FH-Inway** [shashisadasivan/EDMXTrimmer#8]
Very useful tool, thanks.

Instead of using the EntitiesToKeep parameter to specify the entities that should remain in the .edmx file, it would be useful to have a parameter EntitiesToExclude. This would allow to specify a list of entities that should be removed from the .edmx file (e.g. I want to remove all change management entities, but keep the rest).
It would also be nice if both parameters could support wild cards so that e.g. all entities starting with "Vend*" could be kept or excluded.

**Comment by shashisadasivan** [comment]
@FH-Inway i like the wildcard idea. Definitely something to add to this library.
Thanks for using this tool

**Comment by FH-Inway** [comment]
Thanks for considering the request. I created PR #9 to cover it, let me know what you think.
